### ISSUE TITLE
missing arrow

### ISSUE THREAD

**Issue by Warter21** [bernikr/lovelace-notify-card#9]
Hi,
Thanks for your great work. I like your card.
I have a small problem with the arrow button.
it is there and working but it is not visible.
Home Assistant: 2021.12.5
Thanks,
Warter
![notifycard](https://user-images.githubusercontent.com/12511189/147697861-bf91f952-00dd-47b8-8e5a-7584b3f2dc16.png)

**Comment by bernikr** [comment]
Are you using the most recent version of the card? I thought i fixed this already in November 13th.

**Comment by Warter21** [comment]
just for sure I updated it yesterday but it is still missing.

**Comment by Warter21** [comment]
Strange, somehow it looks ok now.

Thanks anyway!
